"""
  The BackItUp demo illustrates the use of fork/join to launch
  parallel actions and synchronize them again. The fork is performed
  by the NullTrans transition with two destinations, while the join is
  performed by the CompletionTrans transition with two sources.

  Behavior: Cozmo backs up by 100 mm while simultaneously beeping. He
  uses DriveForward instead of Forward to avoid conflict with the Say
  action. When he's done backing up, he stops beeping and says 'Safety first'.
"""

try:
    from cozmo_fsm import *
except ImportError:
    raise ImportError("Can't find the cozmo_fsm package. Check your search path.")

class BackItUp(StateNode):
    def setup(self):
        """
            launcher: StateNode() =N=> {driver, speaker}
    
            driver: DriveForward(-100,10)
            speaker: Say('beep',duration_scalar=0.8)
    
            {driver,speaker} =C=> finisher: Say('Safety first!')
    
        """
        
        # Code generated by genfsm on Tue Dec 20 17:19:54 2016:

        launcher = StateNode() .set_name("launcher") .set_parent(self)
        driver = DriveForward(-100,10) .set_name("driver") .set_parent(self)
        speaker = Say('beep',duration_scalar=0.8) .set_name("speaker") .set_parent(self)
        finisher = Say('Safety first!') .set_name("finisher") .set_parent(self)
        
        nulltrans1 = NullTrans() .set_name("nulltrans1")
        nulltrans1 .add_sources(launcher) .add_destinations(driver,speaker)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(driver,speaker) .add_destinations(finisher)
        
        return self
