"""
  The Greet demo illustrates the use of CompletionTrans and TimerTrans
  transitions.

  Behavior: Cozmo starts out by saying 'Greetings, human!'. After his
  speech has completed, he waits 5 seconds, then says 'Bye-bye now'.
"""

try:
    from cozmo_fsm import *
except:
    raise ImportError("Can't find the cozmo_fsm package. Check your search path.")

class Greet(StateMachineProgram):
    def setup(self):
        """
            say: Say('Greetings, human!') =C=>
              wait: StateNode() =T(5)=>
                say2: Say('Bye-bye now.')
        """
        
        # Code generated by genfsm on Wed Jan 25 02:23:47 2017:
        self.name = self.__class__.__name__
        
        say = Say('Greetings, human!') .set_name("say") .set_parent(self)
        wait = StateNode() .set_name("wait") .set_parent(self)
        say2 = Say('Bye-bye now.') .set_name("say2") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(say) .add_destinations(wait)
        
        timertrans1 = TimerTrans(5) .set_name("timertrans1")
        timertrans1 .add_sources(wait) .add_destinations(say2)
        
        return self
