"""
  The Greet demo illustrates the use of CompletionTrans and TimerTrans
  transitions.

  Behavior: Cozmo starts out by saying 'Greetings, human!'. After his
  speech has completed, he waits 5 seconds, then says 'Bye-bye now'.
"""

from cozmo_fsm import *

class Greet(StateMachineProgram):
    def setup(self):
        """
            say: Say('Greetings, human!') =C=>
              wait: StateNode() =T(5)=>
                say2: Say('Bye-bye now.')
        """
        
        # Code generated by genfsm on Mon Feb 17 03:12:53 2020:
        
        say = Say('Greetings, human!') .set_name("say") .set_parent(self)
        wait = StateNode() .set_name("wait") .set_parent(self)
        say2 = Say('Bye-bye now.') .set_name("say2") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(say) .add_destinations(wait)
        
        timertrans1 = TimerTrans(5) .set_name("timertrans1")
        timertrans1 .add_sources(wait) .add_destinations(say2)
        
        return self
