"""
  Example of starting a behavior and indicating that it should not be
  automatically stopped when the behavior node is exited. We later
  use StopBehavior() to stop the behavior.
"""

try:
    from cozmo_fsm import *
except:
    raise ImportError("Can't find the cozmo_fsm package. Check your search path.")

class Look5(StateMachineProgram):
    def setup(self):
        """
            LookAroundInPlace(stop_on_exit=False)
                =T(5)=> Say("I'm almost done")
                =T(5)=> StopBehavior()
        """
        
        # Code generated by genfsm on Wed Jan 25 02:23:47 2017:
        self.name = self.__class__.__name__
        
        lookaroundinplace1 = LookAroundInPlace(stop_on_exit=False) .set_name("lookaroundinplace1") .set_parent(self)
        say1 = Say("I'm almost done") .set_name("say1") .set_parent(self)
        stopbehavior1 = StopBehavior() .set_name("stopbehavior1") .set_parent(self)
        
        timertrans1 = TimerTrans(5) .set_name("timertrans1")
        timertrans1 .add_sources(lookaroundinplace1) .add_destinations(say1)
        
        timertrans2 = TimerTrans(5) .set_name("timertrans2")
        timertrans2 .add_sources(say1) .add_destinations(stopbehavior1)
        
        return self
